In [ ]:
def merge(ls ,start ,mid ,end ):
  ls1=start
  ls2=mid+1
  temp=[]

  while ls1<=mid and ls2<=end:
    if ls[ls1]<=ls[ls2]:
      temp.append(ls[ls1])
      ls1+=1

    else:
      temp.append(ls[ls2])
      ls2+=1

  while ls1<=mid:
    temp.append(ls[ls1])
    ls1+=1

  while ls2<=end:
    temp.append(ls[ls2])
    ls2+=1

  i=0
  j=start

  while j<=end:
    ls[j]=temp[i]
    j+=1
    i+=1

  return

def MergeSort(ls,start,end):
  if end-start<=0:
    return

  else:
    mid=int((start+end)/2)
    MergeSort(ls,start,mid)
    MergeSort(ls,mid+1,end)
    merge(ls,start,mid,end)

  return

def Sort(ls):
  if len(ls)==0:
    return

  else:
    MergeSort(ls,0,len(ls)-1)


In [ ]:
x=[3,1,2]
Sort(x)
print(x)

[1, 2, 3]


In [ ]:
def MinMax(ls):
  if len(ls)==0:
    return

  else:
    return FindMinMax(ls,0,len(ls)-1)

def FindMinMax(ls,start,end):
  if end-start==0:
    return (ls[start],ls[end])

  else:
    mid=int((start+end)/2)
    Ft=FindMinMax(ls,start,mid)
    St=FindMinMax(ls,mid+1,end)
    return (max(Ft[0],St[0]),min(Ft[1],St[1]))

In [ ]:
print(MinMax([1,2,3,4,5,6,7,0,-1,20]))

(20, -1)


In [ ]:
def Karatsuba(first,second):
  Fl=len(str(first))
  Sl=len(str(second))

  if Fl<=2 or Sl<=2:
    return first*second

  else:
    m=int(max(Fl,Sl)/2)
    a=int(first/10**m)
    b=first%(10**m)
    c=int(second/10**m)
    d=second%(10**m)
    C0=Karatsuba(a,c)
    C2=Karatsuba(b,d)
    C1=Karatsuba((a+b),(c+d))-C0-C2
    return C0*(10**(2*m))+C1*(10**m)+C2



In [ ]:
print(Karatsuba(5432,1678))

9114896


In [ ]:
import numpy as np
def Knapsack(Profits,Weights,size):
  if Profits.shape==Weights.shape:
    ProfitPerWeight=Profits/Weights

  indices=np.argsort(ProfitPerWeight)
  Weights=Weights[indices][::-1]
  Profits=Profits[indices][::-1]
  MxProfit=0

  for i in range(Weights.shape[0]):
    if Weights[i]<=size:
      MxProfit+=Profits[i]
      size-=Weights[i]

    else:
      MxProfit+=Profits[i]*size/Weights[i]
      break

  return MxProfit

In [ ]:
P=np.array([5,10,15,7,8,9,4])
W=np.array([1,3,5,4,1,3,2])
size=15
print(Knapsack(P,W,size))

51.0


In [ ]:
def Strassen(A,B):
  if A.shape[0]==2:
    C00=A[0,0]*B[0,0]+A[0,1]*B[1,0]
    C01=A[0,0]*B[0,1]+A[0,1]*B[1,1]
    C10=A[1,0]*B[0,0]+A[1,1]*B[1,0]
    C11=A[1,0]*B[0,1]+A[1,1]*B[1,1]

    return np.array([[C00,C01],[C10,C11]])

  else:
    mid=int(A.shape[0]/2)

    A00=A[0:mid,0:mid]
    A01=A[0:mid,mid:]
    A10=A[mid:,0:mid]
    A11=A[mid:,mid:]

    B00=B[0:mid,0:mid]
    B01=B[0:mid,mid:]
    B10=B[mid:,0:mid]
    B11=B[mid:,mid:]

    P=Strassen(A00 + A11, B00 + B11)
    Q=Strassen(A10 + A11, B00)
    R=Strassen(A00, B01 - B11)
    S=Strassen(A11, B10 - B00)
    T=Strassen(A00 + A01, B11)
    U=Strassen(A10 - A00, B00 + B01)
    V=Strassen(A01 - A11, B10 + B11)

    C00=P+S-T+V
    C01=R+T
    C10=Q+S
    C11=P+R-Q+U

    return np.vstack((np.hstack((C00,C01)),np.hstack((C10,C11))))


In [ ]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12],
    [13,14,15,16]
])

B = np.array([
    [16,15,14,13],
    [12,11,10,9],
    [8, 7, 6, 5],
    [4, 3, 2, 1]
])

print(Strassen(A,B))
C = np.dot(A, B)
print(C)

[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]
[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]


In [ ]:
def MatrixChain(ls):
  Costs=np.zeros((len(ls),len(ls)))
  Bests=np.zeros((len(ls),len(ls)))

  for i in range(len(ls)+1):
    for j in range(len(ls)-i):
      start=j
      end=j+i

      cost=0
      best=j

      for mid in range(j,j+i):
        tcost=0
        tcost=Costs[start,mid]+Costs[mid+1,end]+ls[start][0]*ls[mid][1]*ls[end][1]

        if cost==0:
          cost=tcost

        if tcost<=cost:
          cost=tcost
          best=mid

      Costs[start,end]=cost
      Bests[start,end]=best

  print(Costs)
  print(Bests+1)




In [ ]:
MatrixChain([(5,4),(4,6),(6,2),(2,7)])

[[  0. 120.  88. 158.]
 [  0.   0.  48. 104.]
 [  0.   0.   0.  84.]
 [  0.   0.   0.   0.]]
[[1. 1. 1. 3.]
 [1. 2. 2. 3.]
 [1. 1. 3. 3.]
 [1. 1. 1. 4.]]
